<a href="https://colab.research.google.com/github/Fushionek/MLTraining/blob/main/Supervised/basics/FeatureExtraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
sklearn.__version__

'1.6.1'

In [5]:
def fetch_financial_data(company='AMZN'):
    import pandas_datareader.data as web
    return web.DataReader(name=company, data_source='stooq')

df_raw = fetch_financial_data()
df_raw.head()

               Open    High     Low   Close    Volume
Date
2026-03-13  209.605  210.56  206.22  207.67  35662137
2026-03-12  210.390  211.71  208.15  209.53  44349501
2026-03-11  215.705  217.00  211.35  212.65  34199303
2026-03-10  214.190  215.65  212.43  214.34  35678834
2026-03-09  210.450  213.82  207.11  213.42  54642926

In [7]:
df = df_raw.copy()
df = df[:5] #first 5 rows
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5 entries, 2026-03-13 to 2026-03-09
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    5 non-null      float64
 1   High    5 non-null      float64
 2   Low     5 non-null      float64
 3   Close   5 non-null      float64
 4   Volume  5 non-null      int64
dtypes: float64(4), int64(1)
memory usage: 240.0 bytes

In [8]:
df['day'] = df.index.day
df['month'] = df.index.month
df['year'] = df.index.year
df

               Open    High     Low   Close    Volume  day  month  year
Date
2026-03-13  209.605  210.56  206.22  207.67  35662137   13      3  2026
2026-03-12  210.390  211.71  208.15  209.53  44349501   12      3  2026
2026-03-11  215.705  217.00  211.35  212.65  34199303   11      3  2026
2026-03-10  214.190  215.65  212.43  214.34  35678834   10      3  2026
2026-03-09  210.450  213.82  207.11  213.42  54642926    9      3  2026

In [9]:
df = pd.DataFrame(data={'height' : [175.,178.5,185.,191.,184.5,183.,168.]})
df

   height
0   175.0
1   178.5
2   185.0
3   191.0
4   184.5
5   183.0
6   168.0

In [10]:
df['height_cat'] = pd.cut(x=df.height, bins=3)
df

   height          height_cat
0   175.0  (167.977, 175.667]
1   178.5  (175.667, 183.333]
2   185.0    (183.333, 191.0]
3   191.0    (183.333, 191.0]
4   184.5    (183.333, 191.0]
5   183.0  (175.667, 183.333]
6   168.0  (167.977, 175.667]

In [11]:
df['height_cat'] = pd.cut(x=df.height, bins=(160,175,180,195))

In [12]:
df['height_cat'] = pd.cut(x=df.height, bins=(160,175,180,195), labels=['small','medium','high'])
df

   height height_cat
0   175.0      small
1   178.5     medium
2   185.0       high
3   191.0       high
4   184.5       high
5   183.0       high
6   168.0      small

In [13]:
pd.get_dummies(df, drop_first=True, prefix='height')

   height  height_medium  height_high
0   175.0          False        False
1   178.5           True        False
2   185.0          False         True
3   191.0          False         True
4   184.5          False         True
5   183.0          False         True
6   168.0          False        False

In [14]:
df = pd.DataFrame(data={'lang' : [['PL','ENG'],['GER','ENG','PL','FRA'],['RUS']]})
df

                  lang
0            [PL, ENG]
1  [GER, ENG, PL, FRA]
2                [RUS]

In [15]:
df['lang_number'] = df['lang'].apply(len)
df

                  lang  lang_number
0            [PL, ENG]            2
1  [GER, ENG, PL, FRA]            4
2                [RUS]            1

In [16]:
df['PL_flag'] = df['lang'].apply(lambda x: 1 if 'PL' in x else 0)
df

                  lang  lang_number  PL_flag
0            [PL, ENG]            2        1
1  [GER, ENG, PL, FRA]            4        1
2                [RUS]            1        0

In [17]:
df = pd.DataFrame(data={'website' : ['wp.pl','onet.pl','google.com']})
df

      website
0       wp.pl
1     onet.pl
2  google.com

In [18]:
df.website.str.split('.', expand=True)

        0    1
0      wp   pl
1    onet   pl
2  google  com

In [19]:
n = df.website.str.split('.', expand=True)

In [20]:
df['portal'] = n[0]

In [21]:
df['extension'] = n[1]

In [22]:
df

      website  portal extension
0       wp.pl      wp        pl
1     onet.pl    onet        pl
2  google.com  google       com