<a href="https://colab.research.google.com/github/Fushionek/MLTraining/blob/main/Supervised/basics/Test_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd
import numpy as np

np.random.seed(42)

n_samples = 200

data = {
    'Moc_magiczna': np.random.randint(10, 1000, n_samples),
    'Wiek_artefaktu': np.random.randint(1, 500, n_samples),
    'Rzadkosc': np.random.choice(['Pospolity', 'Rzadki', 'Epicki', 'Mityczny'], n_samples),
    'Waga_kg': np.random.uniform(0.5, 50.0, n_samples),
    'Czy_przeklety': np.random.choice([0, 1], n_samples),
    'Zbedna_Cecha_1': np.random.normal(0, 1, n_samples),
}

df = pd.DataFrame(data)

rarity_map = {'Pospolity': 1, 'Rzadki': 5, 'Epicki': 20, 'Mityczny': 100}
df['Cena_zloto'] = (
    df['Moc_magiczna'] * 2 +
    df['Wiek_artefaktu'] * 0.5 +
    df['Rzadkosc'].map(rarity_map) * 50 +
    np.random.normal(0, 50, n_samples)
)

df.iloc[10:20, 0] = np.nan
df.iloc[50:60, 3] = np.nan

print("Dane gotowe! Masz 200 wierszy i kolumnę 'Cena_zloto' do przewidzenia.")

Dane gotowe! Masz 200 wierszy i kolumnę 'Cena_zloto' do przewidzenia.

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Moc_magiczna    190 non-null    float64
 1   Wiek_artefaktu  200 non-null    int64
 2   Rzadkosc        200 non-null    object
 3   Waga_kg         190 non-null    float64
 4   Czy_przeklety   200 non-null    int64
 5   Zbedna_Cecha_1  200 non-null    float64
 6   Cena_zloto      200 non-null    float64
dtypes: float64(4), int64(2), object(1)
memory usage: 11.1+ KB

In [32]:
df['Rzadkosc'] = df['Rzadkosc'].astype('category')

In [33]:
df.describe()

,Moc_magiczna,Wiek_artefaktu,Waga_kg,Czy_przeklety,Zbedna_Cecha_1,Cena_zloto
count,190.000000,200.000000,190.000000,200.000000,200.000000,200.000000
mean,506.600000,251.405000,25.028450,0.460000,0.073531,2851.303001
std,290.851529,136.198868,14.266291,0.499648,1.159871,2206.523674
min,11.000000,2.000000,1.257575,0.000000,-3.568205,172.075703
25%,255.000000,133.250000,12.943950,0.000000,-0.659449,1173.154836
50%,505.000000,233.500000,24.244702,0.000000,0.152369,1935.968765
75%,775.250000,374.750000,36.696659,1.000000,0.775917,5431.786831
max,996.000000,497.000000,49.798596,1.000000,3.174442,7166.182177

In [34]:
df.isnull().sum()

Moc_magiczna      10
Wiek_artefaktu     0
Rzadkosc           0
Waga_kg           10
Czy_przeklety      0
Zbedna_Cecha_1     0
Cena_zloto         0
dtype: int64

In [35]:
df['Moc_magiczna'].fillna(df['Moc_magiczna'].median(), inplace=True)

/tmp/ipykernel_939/2626077117.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Moc_magiczna'].fillna(df['Moc_magiczna'].median(), inplace=True)

In [36]:
df['Waga_kg'].fillna(df['Waga_kg'].median(), inplace=True)

/tmp/ipykernel_939/2510490727.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Waga_kg'].fillna(df['Waga_kg'].median(), inplace=True)

In [37]:
df

,Moc_magiczna,Wiek_artefaktu,Rzadkosc,Waga_kg,Czy_przeklety,Zbedna_Cecha_1,Cena_zloto
0,112.0,222,Rzadki,21.959277,0,-0.625238,567.173396
1,445.0,485,Rzadki,37.330111,0,-0.273610,1394.414813
2,870.0,407,Rzadki,12.917596,0,1.964253,2165.114048
3,280.0,231,Rzadki,9.624517,1,-0.197222,914.423895
4,116.0,237,Epicki,4.503212,1,-1.226053,1309.067098
...,...,...,...,...,...,...,...
195,752.0,99,Rzadki,13.912403,1,-1.000620,1850.770495
196,250.0,153,Epicki,7.092664,0,2.429848,1645.413739
197,573.0,349,Pospolity,4.271919,1,1.949733,1404.679287
198,105.0,402,Mityczny,47.056325,1,-0.563766,5404.347096
199,909.0,384,Epicki,21.123633,0,-3.568205,3066.283939

In [38]:
df

,Moc_magiczna,Wiek_artefaktu,Rzadkosc,Waga_kg,Czy_przeklety,Zbedna_Cecha_1,Cena_zloto
0,112.0,222,Rzadki,21.959277,0,-0.625238,567.173396
1,445.0,485,Rzadki,37.330111,0,-0.273610,1394.414813
2,870.0,407,Rzadki,12.917596,0,1.964253,2165.114048
3,280.0,231,Rzadki,9.624517,1,-0.197222,914.423895
4,116.0,237,Epicki,4.503212,1,-1.226053,1309.067098
...,...,...,...,...,...,...,...
195,752.0,99,Rzadki,13.912403,1,-1.000620,1850.770495
196,250.0,153,Epicki,7.092664,0,2.429848,1645.413739
197,573.0,349,Pospolity,4.271919,1,1.949733,1404.679287
198,105.0,402,Mityczny,47.056325,1,-0.563766,5404.347096
199,909.0,384,Epicki,21.123633,0,-3.568205,3066.283939

In [40]:
df = pd.get_dummies(df, columns=['Rzadkosc'], drop_first=True)

In [41]:
df

,Moc_magiczna,Wiek_artefaktu,Waga_kg,Czy_przeklety,Zbedna_Cecha_1,Cena_zloto,Rzadkosc_Mityczny,Rzadkosc_Pospolity,Rzadkosc_Rzadki
0,112.0,222,21.959277,0,-0.625238,567.173396,False,False,True
1,445.0,485,37.330111,0,-0.273610,1394.414813,False,False,True
2,870.0,407,12.917596,0,1.964253,2165.114048,False,False,True
3,280.0,231,9.624517,1,-0.197222,914.423895,False,False,True
4,116.0,237,4.503212,1,-1.226053,1309.067098,False,False,False
...,...,...,...,...,...,...,...,...,...
195,752.0,99,13.912403,1,-1.000620,1850.770495,False,False,True
196,250.0,153,7.092664,0,2.429848,1645.413739,False,False,False
197,573.0,349,4.271919,1,1.949733,1404.679287,False,True,False
198,105.0,402,47.056325,1,-0.563766,5404.347096,True,False,False
199,909.0,384,21.123633,0,-3.568205,3066.283939,False,False,False

In [42]:
df.head()

,Moc_magiczna,Wiek_artefaktu,Waga_kg,Czy_przeklety,Zbedna_Cecha_1,Cena_zloto,Rzadkosc_Mityczny,Rzadkosc_Pospolity,Rzadkosc_Rzadki
0,112.0,222,21.959277,0,-0.625238,567.173396,False,False,True
1,445.0,485,37.330111,0,-0.273610,1394.414813,False,False,True
2,870.0,407,12.917596,0,1.964253,2165.114048,False,False,True
3,280.0,231,9.624517,1,-0.197222,914.423895,False,False,True
4,116.0,237,4.503212,1,-1.226053,1309.067098,False,False,False

In [43]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [44]:
cols = ['Moc_magiczna', 'Wiek_artefaktu', 'Waga_kg', 'Zbedna_Cecha_1']
df[cols] = scaler.fit_transform(df[cols])

In [47]:
df.head()

,Moc_magiczna,Wiek_artefaktu,Waga_kg,Czy_przeklety,Zbedna_Cecha_1,Cena_zloto,Rzadkosc_Mityczny,Rzadkosc_Pospolity,Rzadkosc_Rzadki
0,-1.395344,-0.216439,-0.218464,0,-0.603967,567.173396,False,False,True
1,-0.217585,1.719406,0.889785,0,-0.300044,1394.414813,False,False,True
2,1.285562,1.145277,-0.870377,0,1.634205,2165.114048,False,False,True
3,-0.801159,-0.150194,-1.107810,1,-0.234020,914.423895,False,False,True
4,-1.381197,-0.106030,-1.477061,1,-1.123268,1309.067098,False,False,False

In [48]:
from sklearn.model_selection import train_test_split

X = df.drop('Cena_zloto', axis=1)
y = df['Cena_zloto']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [50]:
print(f'Zbior treningowy: {X_train.shape}')
print(f'Zbior testowy: {X_test.shape}')
print(f'Zbior treningowy: {y_train.shape}')
print(f'Zbior testowy: {y_test.shape}')

Zbior treningowy: (160, 8)
Zbior testowy: (40, 8)
Zbior treningowy: (160,)
Zbior testowy: (40,)

In [51]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train,y_train)

LinearRegression()

In [54]:
from sklearn.metrics import mean_absolute_error, r2_score

y_pred = model.predict(X_test)

In [55]:
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error (MAE): {mae}")
print(f"R-squared (R2): {r2}")

Mean Absolute Error (MAE): 65.11750106844777
R-squared (R2): 0.9959915694447877

In [56]:
coefficients = pd.DataFrame(model.coef_,X.columns,columns=['Waga'])
print(coefficients.sort_values(by='Waga',ascending=False))

                           Waga
Rzadkosc_Mityczny   4010.386909
Moc_magiczna         571.371308
Wiek_artefaktu        69.636384
Zbedna_Cecha_1        10.214903
Czy_przeklety          9.659704
Waga_kg                6.959200
Rzadkosc_Rzadki     -744.652175
Rzadkosc_Pospolity  -955.341393

In [59]:
X_simple = X.drop(['Zbedna_Cecha_1', 'Czy_przeklety', 'Waga_kg'], axis=1)

X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(X_simple, y, test_size=0.2, random_state=42)
model_simple = LinearRegression().fit(X_train_s, y_train_s)

print(f"Nowy R2: {r2_score(y_test_s, model_simple.predict(X_test_s)):.4f}")

Nowy R2: 0.9961